// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const String _databaseURL =
      'https://catfisense-db-4cda7-default-rtdb.asia-southeast1.firebasedatabase.app';

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHZ48BQpoY3OkqvG_5A20xFtWyhgPkYx0',
    appId: '1:15270968768:web:ab9ceb9190e6530da0dc25',
    messagingSenderId: '15270968768',
    projectId: 'catfisense-db-4cda7',
    authDomain: 'catfisense-db-4cda7.firebaseapp.com',
    databaseURL: _databaseURL,
    storageBucket: 'catfisense-db-4cda7.firebasestorage.app',
    measurementId: 'G-82JHC0CPXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcLOEZWdWxcRcohECKml8JfqZ8iRzn9o8',
    appId: '1:15270968768:android:376e7b584cf767d4a0dc25',
    messagingSenderId: '15270968768',
    projectId: 'catfisense-db-4cda7',
    databaseURL: _databaseURL,
    storageBucket: 'catfisense-db-4cda7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHNbKkRQU13OzKLsq5EOd7h_DUCUO_TAo',
    appId: '1:15270968768:ios:c278636b50d059b3a0dc25',
    messagingSenderId: '15270968768',
    projectId: 'catfisense-db-4cda7',
    databaseURL: _databaseURL,
    storageBucket: 'catfisense-db-4cda7.firebasestorage.app',
    iosBundleId: 'com.catfisense.catfisense',
  );
}
